name: NVanish
version: '0.1.4'
main: me.ybbbno.nvanish.NVanish
api-version: '1.21'
authors: [ Ybbb ]
dependencies:
  server:
    YBMJ:
      load: BEFORE
      required: true
    nLogin:
      load: BEFORE
      required: false
    voicechat:
      load: BEFORE
      required: false